"""empty message

Revision ID: 349d972bfc6e
Revises: None
Create Date: 2015-06-29 13:55:57.503969

"""

# revision identifiers, used by Alembic.
revision = '349d972bfc6e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.alter_column(
        table_name = 'series',
        column_name = 'memory_verse',
        nullable = False,
        type_ = sa.types.String(250),
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
